### ISSUE TITLE
new warning with servoy 2024.12.0.4023

### ISSUE THREAD

**Issue by r4inX** [Servoy/fullcalendarcomponent2#14]
Hey guys,

so with the latest update of servoy and fc2 i get the following warning/error in my calendar-form.

```WARN com.servoy.j2db.server.ngclient.api - You are calling a component sync api method (to browser) in form 'calendar_timeline' before the form is available in browser's DOM. This should be avoided. (Component : fc , api: getView). Titanim NG client will try to wait for form load only if it sees that it's in the process of showing a form; if not or if the form will not show after a few seconds, it will just fail/ignore the call. NG client used to show the form in a hidden div just in order to be able to call the API. Both can slow down your solution. The solution's code can be changed, or the component's impl could take advantage of server side impl (if a return value is needed, but that value does not necessarily need the form's UI to be loaded in the browser) + model properties, or, if a return value is not needed or can be delayed to a callback param, use async calls with delayUntilFormLoads.```

Everything still works fine but the warning is just stressing me in the log. I tried to move my `onShow()` code (setting the fc-view to a saved cookie) to the `fc.onViewDidMount()` (according to the documentation, this triggers when the fc element is drawn to the DOM) method but the warning still persists.

The warning talks about `api: getView`. In my fc.onDateSet() i just call fc.getView() (which works too, i get the view-object)
It also talks about `delayUntilFormLoads` but i cant find it, its probably a angular-component method.

Below is a output log of the form when it opens. My onShow() is completely empty now. So between the onShow and fcLoading/onViewDidMount something must happen in the component side.

```onLoad()
onShow()
WARN com.servoy.j2db.server.ngclient.api - You are calling a component sync api method (to browser) in form 'calendar_timeline' before the form is available in browser's DOM. This should be avoided. (Component : fc , api: getView). Titanim NG client will try to wait for form load only if it sees that it's in the process of showing a form; if not or if the form will not show after a few seconds, it will just fail/ignore the call. NG client used to show the form in a hidden div just in order to be able to call the API. Both can slow down your solution. The solution's code can be changed, or the component's impl could take advantage of server side impl (if a return value is needed, but that value does not necessarily need the form's UI to be loaded in the browser) + model properties, or, if a return value is not needed or can be delayed to a callback param, use async calls with delayUntilFormLoads.
WARN com.servoy.j2db.server.ngclient.api - You are calling a component sync api method (to browser) in form 'calendar_timeline' before the form is available in browser's DOM. This should be avoided. (Component : fc , api: getView). Titanim NG client will try to wait for form load only if it sees that it's in the process of showing a form; if not or if the form will not show after a few seconds, it will just fail/ignore the call. NG client used to show the form in a hidden div just in order to be able to call the API. Both can slow down your solution. The solution's code can be changed, or the component's impl could take advantage of server side impl (if a return value is needed, but that value does not necessarily need the form's UI to be loaded in the browser) + model properties, or, if a return value is not needed or can be delayed to a callback param, use async calls with delayUntilFormLoads.
onFcLoading()
onViewDidMount()
onDateSet()
```

Im on the lastest commit of fc2.
Any ideas on what this is or how i can fix this? Some knowledge would be great! 

Thanks

**Comment by jcompagner** [comment]
why are you wanting to save that in onshow?
isn't the idea to call then in the onhide and then store it? why do you want to store the initial view?

That error is reported by servoy already for a long time, and also getView() is already like this (sync api call) for a long time in the component so not sure why you now suddenly get that (so it could be that we mark the form a bit later now that it is visible)
But the onViewMount should kind of work, but i have an idea that this is something that is already fixed, i will check this
because in onViewMound the form should be in attached mode

**Comment by r4inX** [comment]
im storing the cookie at onDateSet() and restoring it onViewDidMount() (moved from onShow()) because the calendar forgot which viewtype and currentDate it had after switching the form and going back (<- fixed by now with the latest commits so thanks) and also initialView was broken if used with customViews (<- didnt check if its still broken)

Youre right about the saving of the cookie and currentStart, this can be moved to onHide() away from onDateSet(). Ty for that

i mean everything works as it should. just wanted to report it to you guys because i noticed this error popping up after updating servoy. I can live with the error/warning for now

**Comment by r4inX** [comment]
i found the origin of the warning.

in my calendar-options-object i have a eventSource function whichs fetches the events for the shown view.

```
	// --- get the selected view-dates ---
	var _start = scopes.svyDateUtils.getFirstDayOfWeek()
	var _end	= scopes.svyDateUtils.getLastDayOfWeek()
	
	if(calendar){
		if(calendar.getView()){     \\ <- first warning appears here, but we are true
			/** @type {CustomType<svy-fullcalendar2.ViewType>} */
			var _view = calendar.getView()      \\ <- second warning appears here, but we still get the viewObject
			
			_start 	= _view.activeStart
			_end 	= _view.activeEnd
		}
	}
```
thats where the warning is fired. I just load the events which are needed for the shown view (1week, 2week, 1month, etc) to load less data. So at the firstShow the warning fires because it thinks the element is not loaded yet.

i now fixed it with a default _firstShow variable around the calendar-if, its a bit heckymecky (onShow sets to true, after onViewDidMount sets it to false) but it works. Warning is not appearing anymore.
